### ISSUE TITLE
Archlinux无效?

### ISSUE THREAD

**Issue by phoon** [lolimay/shadowsocks-deepin#1]
你好，我是在Archlinux上编译的，然后全局代理无效，目前还得通过浏览器插件。终端运行主要看到了两个报错:
"dtkwidget2" can not find qm files
"shadowsocks-client" can not find qm files
求指点

**Comment by shiqimei** [comment]
请下载 release 页的 v1.2.1版本然后自行编译

**Comment by phoon** [comment]
依旧无效，算了，不折腾了:sleepy:

**Comment by shiqimei** [comment]
请问现在是如何报错的呢？

**Comment by phoon** [comment]
和之前一样

**Comment by shiqimei** [comment]
由于我这边没有 arch，无法帮你调试，抱歉了！

**Comment by phoon** [comment]
还是谢谢了:smile:
