### ISSUE TITLE
点击程序图标无反应

### ISSUE THREAD

**Issue by xinyangmaojian** [lolimay/shadowsocks-deepin#12]
下载下来1.2.1和1.2.2，双击影梭图标，鼠标会变成加载那种图标，等一会鼠标恢复正常    启动不了。
再双击图标，还是 这样

**Comment by shiqimei** [comment]
那个可能你没用过Windows版本的小飞机。小飞机的正确开启方式是右击小飞机图标。

**Comment by xinyangmaojian** [comment]
> 那个可能你没用过Windows版本的小飞机。小飞机的正确开启方式是右击小飞机图标。

还能这样操作？？？   windows我都双击的打开的啊     只是在打开运行后，右击右下角的小飞机  会弹出来个弹框  里边有切换服务器  切换pac服务器啥的 。。。

回去试试右击deepin里的小飞机    看能不能打开

**Comment by xinyangmaojian** [comment]
![1](https://user-images.githubusercontent.com/26449547/46012580-4a8f5880-c0fc-11e8-990e-e82260a73208.png)
我右键点击是这样的啊？  如果选择打开    鼠标是那种正在启动的样子  等一会恢复成正常的样子，但是也没有打开小飞机

**Comment by shiqimei** [comment]
你好，是下载deb包安装后启动。

**Comment by xinyangmaojian** [comment]
![1](https://user-images.githubusercontent.com/26449547/46012815-f5a01200-c0fc-11e8-8bb8-86d51da319db.png)
我点击下载，是这样的。能给个deb包吗？

不好意思哈，小白不会玩这些，所以啰嗦了些，添麻烦了。

**Comment by shiqimei** [comment]
#10

**Comment by xinyangmaojian** [comment]
好的  谢谢。

**Comment by xinyangmaojian** [comment]
很好用，支持支持。
