### ISSUE TITLE
小飞机不能启动了

### ISSUE THREAD

**Issue by jeesk** [lolimay/shadowsocks-deepin#14]
昨天安装了一次，小飞机是可以连接成功的。 但是今天我软件都不能打开了，重启电脑，和卸载了重新安装也是不行的， 我需要提供哪些日志信息，日志信息在什么地方查找

**Comment by shiqimei** [comment]
你好，先退出已经在运行的小飞机，再在终端中输入 `shadowsocks-deepin` 即可看到日志。如果上传日志请记得将敏感信息去掉。

**Comment by jeesk** [comment]
> 你好，先退出已经在运行的小飞机，再在终端中输入 `shadowsocks-deepin` 即可看到日志。如果上传日志请记得将敏感信息去掉。

问题已经解决了
