### ISSUE TITLE
自己编译改pac地址的遇到问题

### ISSUE THREAD

**Issue by YLXDXX** [lolimay/shadowsocks-deepin#21]
我修改了src下MainWindow.cpp文件里的pac地址，但是编译出的程序运行后pac地址依然是：http://file.lolimay.cn/autoproxy.pac
请问解决之法？

**Comment by shiqimei** [comment]
把 .config目录下的小飞机配置文件全删除了试试

**Comment by YLXDXX** [comment]
谢谢，ok了
