### ISSUE TITLE
打开就报start fail, 有日志吗？

### ISSUE THREAD

**Issue by jay763190097** [lolimay/shadowsocks-deepin#25]
![_ _20190108001333](https://user-images.githubusercontent.com/16317178/50779040-50d7c800-12da-11e9-9256-f30507dda5a5.png)

![_ _20190108001333](https://user-images.githubusercontent.com/16317178/50779005-3e5d8e80-12da-11e9-83bb-5dd9df6942b1.png)

最新的自己打的包，也有这个问题

**Comment by shiqimei** [comment]
在命令行启动 `shadowsocks-deepin` 会有日志
