### ISSUE TITLE
manjaro deepin 可以使用吗

### ISSUE THREAD

**Issue by jianchengwang** [lolimay/shadowsocks-deepin#28]

**Comment by shiqimei** [comment]
把相关的依赖都装上应该是可以用的，没有测试过。

**Comment by shiqimei** [comment]
请使用 https://github.com/lolimay/shadowsocks-deepin/releases/tag/V1.2.2-beat 这份源码打包，由于我个人没用过 arch 系，打包方法麻烦自己摸索啦～

**Comment by jianchengwang** [comment]
> 请使用 https://github.com/lolimay/shadowsocks-deepin/releases/tag/V1.2.2-beat 这份源码打包，由于我个人没用过 arch 系，打包方法麻烦自己摸索啦～
谢啦，我试下
