### ISSUE TITLE
提示：timeout is 0,we will change the value to 6.

### ISSUE THREAD

**Issue by shareven** [lolimay/shadowsocks-deepin#29]
图标是灰色的，配置了服务器后，打开软件报错，也无法代理
![image](https://user-images.githubusercontent.com/25793040/51439150-123a0880-1cf1-11e9-999a-affdc2fd9e74.png)

**Comment by shiqimei** [comment]
这个是未设置默认延迟导致的，已经默认为你设置6秒了。不影响正常使用的。
