### ISSUE TITLE
系统升级15.7后无法修改服务器配置

### ISSUE THREAD

**Issue by Rainpan** [lolimay/shadowsocks-deepin#3]
1.原先已经配置三个服务器了，现在需要修改相关信息，修改完后选择相应服务器软件直接退出，日志没有显示异常
2.如果修改或删除配置后，退出再重新打开软件配置仍然是原先旧的三个服务配置

**Comment by Rainpan** [comment]
3.即使在原先的配置修改不异常退出，但是代理的仍然是旧的配置不能正常连接

**Comment by shiqimei** [comment]
您好，我目前也是15.7。我试着添加、编辑和删除服务器配置，功能是正常的，没有复现出您所说的问题。您是不是更改了用户名或者进行了其它的一些操作而导致找不到正确的配置文件呢？

目前你可以通过手动编辑配置文件解决更新服务器配置的问题：
配置文件路径 `/home/你的用户名/.config/pikachu/shadowsocks-client/gui-config.json`

**Comment by Rainpan** [comment]
~~有点崩盘的感觉,因为系统升级完后软件里面基本所有操作好像都是无效的, 我看了一下配置文件,gui-conf.json没有相关配置,但config.conf有三条类似的数据,并且不是明文,所以我感觉可能是系统升级导致一些莫名其妙的bug,现在准备删除配置及软件重新安装试一下.

**Comment by shiqimei** [comment]
恩，删除配置文件后卸载重装试试。

**Comment by Rainpan** [comment]
重新安装后服务正常了。
不过从1.1.0版本就有个问题是有时修改配置后更换服务器会直接崩溃退出了,重新打开就好了。
