### ISSUE TITLE
15.7版本版本上不能使用，全局还是pac 都不能正常使用．

### ISSUE THREAD

**Issue by wuhujun** [lolimay/shadowsocks-deepin#30]
15.7版本版本上不能使用，全局还是pac 都不能正常使用．

**Comment by shiqimei** [comment]
请在终端中启动 `shadowsocks-deepin` 看下日志

**Comment by wuhujun** [comment]
后来解决了，google 浏览器可以，firefox 显示超时，感觉是代理的本地端口信息没有被firefox 浏览器识别到．

**Comment by shiqimei** [comment]
Firefox 需要配合 [Proxychains](https://github.com/haad/proxychains) 强制使其 TCP 连接强制走 socks5 代理。
