### ISSUE TITLE
换服务器时闪退

### ISSUE THREAD

**Issue by MAOKO1993** [lolimay/shadowsocks-deepin#31]
在深度Linux系统打开影梭，每次切换服务器时都会闪退。

**Comment by shiqimei** [comment]
这是个老 bug 了，一直没时间修...

**Comment by littlelk** [comment]
在深度下，我怎么没办法添加服务器，每次手动配置后都会闪退

**Comment by shiqimei** [comment]
> 在深度下，我怎么没办法添加服务器，每次手动配置后都会闪退

请单开 issue，以便更好地追踪问题。
