### ISSUE TITLE
编辑服务器保存后无效,并没有保存修改

### ISSUE THREAD

**Issue by zoze0** [lolimay/shadowsocks-deepin#36]
当前最新版 , deepin15.9.1
编辑服务器保存后无效,并没有保存修改

**Comment by zoze0** [comment]
![_ _20190214172118](https://user-images.githubusercontent.com/20562449/52776825-641a4800-307d-11e9-9ec4-70a393738c11.gif)

**Comment by shiqimei** [comment]
你是自己的编译打包的吗，还是使用1.2.2版本的呢?

这个是已修复部分bug的准1.3版本，可以试试:

[shadowsocks-deepin-1.3.0_pre.tar.gz](https://github.com/lolimay/shadowsocks-deepin/files/2864235/shadowsocks-deepin-1.3.0_pre.tar.gz)

> !!! 安装之前请先使用 `sudo apt purge shadowsocks-deepin -y` 完全卸载之前的版本

**Comment by shiqimei** [comment]
仔细看了你的截图，发现是你的操作问题 <img height="20" src="https://user-images.githubusercontent.com/32427260/52777564-156dad80-307f-11e9-8bdf-82de9f623e00.png"/>

请先点击左边的 <kbd>添加</kbd> 按钮 (新版本中是 <kbd>新建</kbd> )，然后再编辑服务器配置。

**Comment by zoze0** [comment]
我这个操作确实有问题,应该添加,已经可以, 但是之前已经有配置的情况下,我修改配置再保存再次打开还是无效.还是原来的老配置,所以我才卸载然后下载的新版本.
那等后面新版出了再看情况反馈吧,

**Comment by Var-iazioni** [comment]
这个问题我也遇到了。。还有启动代理闪退的问题。。
然后删了下了个最新版就可以了。。

**Comment by zoze0** [comment]
我的是多个代理切换时代理闪退,概率有80%
