### ISSUE TITLE
无法打开'debian/changelog

### ISSUE THREAD

**Issue by rt-95** [lolimay/shadowsocks-deepin#48]
如题，按照步骤进行到最后一步时爆错误
tail: 无法打开'debian/changelog' 读取数据: 没有那个文件或目录
dpkg-buildpackage: error: tail of debian/changelog subprocess returned exit status 1

**Comment by shiqimei** [comment]
是直接用 master 分支的代码编译的吗？源码已经更新了，但是文档编译文档还是之前的。

如果需要自行编译使用的话，请用 release 页中的代码编译。

**Comment by rt-95** [comment]
------------------ 原始邮件 ------------------
发件人: "lolimay"<notifications@github.com>;
发送时间: 2019年6月10日(星期一) 晚上8:36
收件人: "lolimay/shadowsocks-deepin"<shadowsocks-deepin@noreply.github.com>;
抄送: "kobe@"<1197574017@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lolimay/shadowsocks-deepin] 无法打开'debian/changelog (#48)




是直接用 master 分支的代码编译的吗？源码已经更新了，但是文档编译文档还是之前的。
 
如果需要自行编译使用的话，请用 release 页中的代码编译。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

好的，我大概明白了，我没用master分支，感谢感谢！
