### ISSUE TITLE
shadowsocks-deepin pac模式，不生效.

### ISSUE THREAD

**Issue by echollzq** [lolimay/shadowsocks-deepin#50]
我也是今天才发现的，使用pac模式，不生效（之前都是正常的），只有用全局模式，才正常。
pac模式 应该用的是远程的pac文件，估计是远程地址挂掉了？所以导致pac模式无用？
如果能用本地的pac文件，或者自定义url地址就好了。

**Comment by echollzq** [comment]
在deepin的网络代理里
发现一个url:http://file.lolimay.cn/autoproxy.pac   
这个url已经无法访问了。

尝试替换其他可用的pac 依然不行，只能先 全局模式凑合了。

**Comment by shiqimei** [comment]
旧域名地址已失效，在紧急修复中，抱歉！

**Comment by gmaso** [comment]
还以为被xx了，折腾半天发现全局模式还能用
