### ISSUE TITLE
打包成deb时出现错误

### ISSUE THREAD

**Issue by simplaj** [lolimay/shadowsocks-deepin#6]
前面进行顺利，但在打包成deb时报错了，请问您
![_ _20180909142416](https://user-images.githubusercontent.com/39286060/45261888-cae76580-b43c-11e8-9653-c8c100f9ac8a.png)
我这是什么问题

**Comment by shiqimei** [comment]
缺少 cmake 等依赖。先装个 cmake 看看：
````bash
sudo apt install cmake -y
````

**Comment by simplaj** [comment]
我
![_20180909143742](https://user-images.githubusercontent.com/39286060/45261939-4a296900-b43e-11e8-8766-7debd0c4da18.png)
装完cmake后是这样的

**Comment by simplaj** [comment]
`apt -f -y install`执行这个后也没有变化

**Comment by shiqimei** [comment]
`dh_make --version` 看看你的 dh-make 版本
`fakeroot --version` 看看你的 fakeroot 版本

**Comment by shiqimei** [comment]
我刚刚测试了两遍，打包都是正常的。目前只能猜测你可能是缺少了什么依赖。

另外，请问你的打包方法是依照这个的吗？
![](http://images.lolimay.cn/18-9-9/94578060.jpg)

**Comment by simplaj** [comment]
![_20180909150746](https://user-images.githubusercontent.com/39286060/45262098-3d0e7900-b442-11e8-90d6-a7683fdcafc4.png)

**Comment by simplaj** [comment]
我是按照您的教程来的
![_20180909151008](https://user-images.githubusercontent.com/39286060/45262104-7941d980-b442-11e8-8dbd-11864bebc558.png)

**Comment by shiqimei** [comment]
````
sudo apt install qt5-default qttools5-dev-tools qt5-qmake g++ qtcreator -y
sudo apt install libdtkbase-dev libdtkwidget-dev -y
sudo apt install libdframeworkdbus-dev -y
sudo apt install libqrencode-dev libzbar-dev -y
sudo apt install libdtkbase-dev libdtkcore-dev libdtksettings-dev libdtksettingsview-dev libdtkutil-dev libdtkwidget-dev libdtkwm-dev -y
sudo apt install dh-make fakeroot -y
````
试试把开发所需的所有依赖全装上，再打包看看

**Comment by simplaj** [comment]
这两版有些不同，我装个fakeroot试下

**Comment by shiqimei** [comment]
应该和 fakeroot 没什么关系，如果是缺少 fakeroot 应该一开始就会提示。

**Comment by simplaj** [comment]
是的，我在逐步装上面的依赖，谢谢您

**Comment by simplaj** [comment]
装上以上依赖后仍不成功
![_20180909152950](https://user-images.githubusercontent.com/39286060/45262239-bd82a900-b445-11e8-904b-dfc1a58e7524.png)
请问这个错误代码意味着什么

**Comment by shiqimei** [comment]
你试试这个
![](http://images.lolimay.cn/18-9-9/21381639.jpg)
看看能不能正常构建出二进制可执行程序并正常执行

**Comment by kingskill** [comment]
`king@king-PC:~/Downloads/shadowsocks/shadowsocks-deepin-1.2.2/build$ cmake ..

process translations/shadowsocks-client_en.ts
Updating 'translations/shadowsocks-client_en.qm'...
    Generated 0 translation(s) (0 finished and 0 unfinished)
    Ignored 102 untranslated source text(s)

process translations/shadowsocks-client_zh.ts
Updating 'translations/shadowsocks-client_zh.qm'...
    Generated 106 translation(s) (106 finished and 0 unfinished)
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  src/CMakeLists.txt:22 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/king/Downloads/shadowsocks/shadowsocks-deepin-1.2.2/build/CMakeFiles/CMakeOutput.log".
`

**Comment by shiqimei** [comment]
把依赖先装上试试
````
sudo apt install qtcreator-dde qttools5-dev -y
````

**Comment by kingskill** [comment]
> 把依赖先装上试试
> 
> ```
> sudo apt install qtcreator-dde qttools5-dev -y
> ```

哇哇，老大，这回可以了！似乎就是这两个其中一个。

另外，编译出来界面是英文的？

**Comment by shiqimei** [comment]
国庆应该能搞好

**Comment by Graundcian** [comment]
请问大佬manjaro-deepin 可以用吗

**Comment by shiqimei** [comment]
没测试过，不过可以下载安装试试。缺什么依赖都给安装上。

**Comment by jay763190097** [comment]
@kingskill 有达成deb包么？我还是报你同样的错误！！！
