### ISSUE TITLE
扫描二维码或者链接解析有问题

### ISSUE THREAD

**Issue by mymartin** [lolimay/shadowsocks-deepin#9]
感谢作者～
我使用的免费账户解析有问题。（逗比根据地）
![image](https://user-images.githubusercontent.com/6276117/45911764-20af0b00-be4a-11e8-8e54-ddbe2f70e79c.png)
图中链接：ss://Y2hhY2hhMjA6ZG91Yi5pby9zc3poZngvKjE2MTdANDUuNjIuMjM4LjE0NzoxNjE3
和二维码扫描出来，密码和ip位置填写错误。
不知道是这个站点的问题，还是解析的地方有问题，望修复。

**Comment by shiqimei** [comment]
你好，这个BUG会在新版中修复，感谢你的issue。
